[2018-11-18 05:12:15 +0000] [10139] [INFO] Listening at: http://127.0.0.1:8000 (10139)
[2018-11-18 05:12:15 +0000] [10139] [INFO] Using worker: sync
[2018-11-18 05:12:15 +0000] [10143] [INFO] Booting worker with pid: 10143
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:12:16.557261: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:12:16.558535: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:27:43 +0000] [10139] [INFO] Handling signal: term
[2018-11-18 05:27:43 +0000] [10143] [INFO] Worker exiting (pid: 10143)
looking for food in files/CMTKPBF.png
looking for food in files/CMTKPBF.png
looking for food in files/NU91NXP.png
looking for food in files/NU91NXP.png
[2018-11-18 05:27:43 +0000] [10139] [INFO] Shutting down: Master
[2018-11-18 05:27:45 +0000] [10271] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:27:45 +0000] [10271] [INFO] Listening at: http://127.0.0.1:8000 (10271)
[2018-11-18 05:27:45 +0000] [10271] [INFO] Using worker: sync
[2018-11-18 05:27:45 +0000] [10275] [INFO] Booting worker with pid: 10275
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:27:46.496315: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:27:46.497550: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:30:36 +0000] [10271] [INFO] Handling signal: term
[2018-11-18 05:30:36 +0000] [10275] [INFO] Worker exiting (pid: 10275)
[2018-11-18 05:30:37 +0000] [10271] [INFO] Shutting down: Master
[2018-11-18 05:30:38 +0000] [10432] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:30:38 +0000] [10432] [INFO] Listening at: http://127.0.0.1:8000 (10432)
[2018-11-18 05:30:38 +0000] [10432] [INFO] Using worker: sync
[2018-11-18 05:30:38 +0000] [10436] [INFO] Booting worker with pid: 10436
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:30:39.727134: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:30:39.728416: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:39:05 +0000] [10432] [INFO] Handling signal: term
[2018-11-18 05:39:05 +0000] [10436] [INFO] Worker exiting (pid: 10436)
[2018-11-18 05:39:05 +0000] [10432] [INFO] Shutting down: Master
[2018-11-18 05:39:06 +0000] [10586] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:39:06 +0000] [10586] [INFO] Listening at: http://127.0.0.1:8000 (10586)
[2018-11-18 05:39:06 +0000] [10586] [INFO] Using worker: sync
[2018-11-18 05:39:06 +0000] [10590] [INFO] Booting worker with pid: 10590
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:39:07.875440: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:39:07.876656: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:39:20,371] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 43, in upload_file
    images = filesFromDB(minRow, maxRow)
  File "/home/ubuntu/SeeFood-Server/index.py", line 138, in filesFromDB
    (minRow, maxRow)
TypeError: %d format: a number is required, not NoneType
[2018-11-18 05:39:26,633] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 43, in upload_file
    images = filesFromDB(minRow, maxRow)
  File "/home/ubuntu/SeeFood-Server/index.py", line 138, in filesFromDB
    (minRow, maxRow)
TypeError: %d format: a number is required, not NoneType
[2018-11-18 05:41:39 +0000] [10586] [INFO] Handling signal: term
[2018-11-18 05:41:39 +0000] [10590] [INFO] Worker exiting (pid: 10590)
[2018-11-18 05:41:39 +0000] [10586] [INFO] Shutting down: Master
[2018-11-18 05:41:41 +0000] [10695] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:41:41 +0000] [10695] [INFO] Listening at: http://127.0.0.1:8000 (10695)
[2018-11-18 05:41:41 +0000] [10695] [INFO] Using worker: sync
[2018-11-18 05:41:41 +0000] [10699] [INFO] Booting worker with pid: 10699
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:41:42.459862: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:41:42.461072: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:41:45,758] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 53, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-18 05:42:55 +0000] [10695] [INFO] Handling signal: term
[2018-11-18 05:42:55 +0000] [10699] [INFO] Worker exiting (pid: 10699)
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0','50000'' at line 1")
[2018-11-18 05:42:55 +0000] [10695] [INFO] Shutting down: Master
[2018-11-18 05:42:57 +0000] [10804] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:42:57 +0000] [10804] [INFO] Listening at: http://127.0.0.1:8000 (10804)
[2018-11-18 05:42:57 +0000] [10804] [INFO] Using worker: sync
[2018-11-18 05:42:57 +0000] [10808] [INFO] Booting worker with pid: 10808
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:42:58.146036: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:42:58.147842: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:43:01,568] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 53, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-18 05:44:08 +0000] [10804] [INFO] Handling signal: term
[2018-11-18 05:44:08 +0000] [10808] [INFO] Worker exiting (pid: 10808)
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0','50000'' at line 1")
[2018-11-18 05:44:09 +0000] [10804] [INFO] Shutting down: Master
[2018-11-18 05:44:10 +0000] [10914] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:44:10 +0000] [10914] [INFO] Listening at: http://127.0.0.1:8000 (10914)
[2018-11-18 05:44:10 +0000] [10914] [INFO] Using worker: sync
[2018-11-18 05:44:10 +0000] [10918] [INFO] Booting worker with pid: 10918
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:44:11.484097: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:44:11.485361: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:44:14,812] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-18 05:47:04 +0000] [10914] [INFO] Handling signal: term
[2018-11-18 05:47:04 +0000] [10918] [INFO] Worker exiting (pid: 10918)
None
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0','50000'' at line 1")
filesFromDB Failed
[2018-11-18 05:47:05 +0000] [10914] [INFO] Shutting down: Master
[2018-11-18 05:47:06 +0000] [11023] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:47:06 +0000] [11023] [INFO] Listening at: http://127.0.0.1:8000 (11023)
[2018-11-18 05:47:06 +0000] [11023] [INFO] Using worker: sync
[2018-11-18 05:47:06 +0000] [11029] [INFO] Booting worker with pid: 11029
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:47:07.492841: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:47:07.494175: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 05:48:37,417] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 46, in upload_file
    images = filesFromDB(minRow, maxRow)
  File "/home/ubuntu/SeeFood-Server/index.py", line 144, in filesFromDB
    (minRow, maxRow)
TypeError: %d format: a number is required, not unicode
[2018-11-18 05:50:54 +0000] [11023] [INFO] Handling signal: term
[2018-11-18 05:50:54 +0000] [11029] [INFO] Worker exiting (pid: 11029)
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394]]
1
[2018-11-18 05:50:54 +0000] [11023] [INFO] Shutting down: Master
[2018-11-18 05:50:55 +0000] [11141] [INFO] Starting gunicorn 19.9.0
[2018-11-18 05:50:55 +0000] [11141] [INFO] Listening at: http://127.0.0.1:8000 (11141)
[2018-11-18 05:50:55 +0000] [11141] [INFO] Using worker: sync
[2018-11-18 05:50:55 +0000] [11145] [INFO] Booting worker with pid: 11145
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-18 05:50:56.796346: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-18 05:50:56.797575: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-18 23:51:40,562] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-18 23:53:52,624] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-19 00:08:59,716] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-19 00:09:30,253] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-20 17:02:24,115] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-20 17:02:54,605] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-20 17:04:33,672] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-20 17:10:18,712] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 111, in fileToDB
    # Oh no we fucked up, gotta roll back to a previous DB version
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-20 17:10:31 +0000] [11141] [INFO] Handling signal: term
[2018-11-20 17:10:31 +0000] [11145] [INFO] Worker exiting (pid: 11145)
1
[['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394]]
0
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394]]
0
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394]]
1
[['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394]]
0
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394]]
looking for food in files/VRHCN25.jpg
looking for food in files/4T3HQCE.jpg
looking for food in files/STVGX8L.jpg
looking for food in files/NWI4M7O.jpg
looking for food in files/4NPCA1P.png
looking for food in files/9VDTDTW.png
looking for food in files/TZ2537A.png
looking for food in files/VZPAM9Z.png
[2018-11-20 17:10:31 +0000] [11141] [INFO] Shutting down: Master
[2018-11-20 17:10:33 +0000] [23816] [INFO] Starting gunicorn 19.9.0
[2018-11-20 17:10:33 +0000] [23816] [INFO] Listening at: http://127.0.0.1:8000 (23816)
[2018-11-20 17:10:33 +0000] [23816] [INFO] Using worker: sync
[2018-11-20 17:10:33 +0000] [23820] [INFO] Booting worker with pid: 23820
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-20 17:10:36.417849: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-20 17:10:36.422155: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-20 17:13:39 +0000] [23816] [INFO] Handling signal: term
[2018-11-20 17:13:39 +0000] [23820] [INFO] Worker exiting (pid: 23820)
looking for food in files/YPSZCYT.png
looking for food in files/YPSZCYT.png
looking for food in files/UAC3D1S.jpg
looking for food in files/UAC3D1S.jpg
[2018-11-20 17:13:40 +0000] [23816] [INFO] Shutting down: Master
[2018-11-20 17:13:41 +0000] [23930] [INFO] Starting gunicorn 19.9.0
[2018-11-20 17:13:41 +0000] [23930] [INFO] Listening at: http://127.0.0.1:8000 (23930)
[2018-11-20 17:13:41 +0000] [23930] [INFO] Using worker: sync
[2018-11-20 17:13:41 +0000] [23938] [INFO] Booting worker with pid: 23938
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-20 17:13:43.316618: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-20 17:13:43.317481: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394],[2018-11-22 04:03:17,882] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-22 04:13:55,229] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-22 20:39:41,076] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-22 20:41:06,111] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 112, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-22 20:41:13,848] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    zf.write(individualFile[1], basename(individualFile[1]))
IndexError: string index out of range
[2018-11-26 14:41:26 +0000] [23930] [INFO] Handling signal: term
[2018-11-26 14:41:26 +0000] [23938] [INFO] Worker exiting (pid: 23938)
 ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
[['loaded_fries', 'files/CMTKPBF.png', 2.62416, -0.559394], ['loaded_fries', 'files/NU91NXP.png', 2.62416, -0.559394], ['test', 'files/YPSZCYT.png', 0.208258, 1.85312], ['test', 'files/UAC3D1S.jpg', 1.76711, 0.293466]]
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
looking for food in files/1CP6PX5.jpg
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
[2018-11-26 14:41:26 +0000] [23930] [INFO] Shutting down: Master
[2018-11-26 14:41:28 +0000] [14218] [INFO] Starting gunicorn 19.9.0
[2018-11-26 14:41:28 +0000] [14218] [INFO] Listening at: http://127.0.0.1:8000 (14218)
[2018-11-26 14:41:28 +0000] [14218] [INFO] Using worker: sync
[2018-11-26 14:41:28 +0000] [14222] [INFO] Booting worker with pid: 14222
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-26 14:41:30.895595: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-26 14:41:30.899332: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-26 14:42:54,294] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 56, in upload_file
    conf_score = abs(scores[0,0] - scores[0,1])
TypeError: list indices must be integers, not tuple
[2018-11-26 14:47:47 +0000] [14218] [INFO] Handling signal: term
[2018-11-26 14:47:47 +0000] [14222] [INFO] Worker exiting (pid: 14222)
looking for food in files/6NXLFUP.jpg
looking for food in files/6NXLFUP.jpg
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
[2018-11-26 14:47:48 +0000] [14218] [INFO] Shutting down: Master
[2018-11-26 14:47:49 +0000] [14334] [INFO] Starting gunicorn 19.9.0
[2018-11-26 14:47:49 +0000] [14334] [INFO] Listening at: http://127.0.0.1:8000 (14334)
[2018-11-26 14:47:49 +0000] [14334] [INFO] Using worker: sync
[2018-11-26 14:47:49 +0000] [14338] [INFO] Booting worker with pid: 14338
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-26 14:47:51.830389: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-26 14:47:51.831185: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-26 14:47:56,635] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 56, in upload_file
    conf_score = abs(scores[0,0] - scores[0,1])
TypeError: list indices must be integers, not tuple
[2018-11-26 14:50:17 +0000] [14334] [INFO] Handling signal: term
[2018-11-26 14:50:17 +0000] [14338] [INFO] Worker exiting (pid: 14338)
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
[2018-11-26 14:50:17 +0000] [14334] [INFO] Shutting down: Master
[2018-11-26 14:50:19 +0000] [14444] [INFO] Starting gunicorn 19.9.0
[2018-11-26 14:50:19 +0000] [14444] [INFO] Listening at: http://127.0.0.1:8000 (14444)
[2018-11-26 14:50:19 +0000] [14444] [INFO] Using worker: sync
[2018-11-26 14:50:19 +0000] [14453] [INFO] Booting worker with pid: 14453
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-26 14:50:20.825636: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-26 14:50:20.826455: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-27 21:25:23,899] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-27 21:25:29,917] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 00:20:24,811] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 00:20:40,895] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:30:22,048] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:30:47,692] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:33:05,593] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:33:33,683] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:34:10,985] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:37:13,043] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:39:15,470] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:39:22,598] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:44:13,657] ERROR in app: Exception on /upload [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 55, in upload_file
    scores = [individualFile[2], individualFile[3]]
IndexError: string index out of range
[2018-11-28 04:47:56 +0000] [14444] [INFO] Handling signal: term
[2018-11-28 04:47:56 +0000] [14453] [INFO] Worker exiting (pid: 14453)
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
[2018-11-28 04:47:57 +0000] [14444] [INFO] Shutting down: Master
[2018-11-28 04:47:58 +0000] [18643] [INFO] Starting gunicorn 19.9.0
[2018-11-28 04:47:58 +0000] [18643] [INFO] Listening at: http://127.0.0.1:8000 (18643)
[2018-11-28 04:47:58 +0000] [18643] [INFO] Using worker: sync
[2018-11-28 04:47:58 +0000] [18647] [INFO] Booting worker with pid: 18647
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-28 04:48:01.011881: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-28 04:48:01.014922: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-28 05:59:59 +0000] [18643] [INFO] Handling signal: term
[2018-11-28 05:59:59 +0000] [18647] [INFO] Worker exiting (pid: 18647)
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872]]
looking for food in files/70O9QGR.jpg
looking for food in files/70O9QGR.jpg
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
[2018-11-28 05:59:59 +0000] [18643] [INFO] Shutting down: Master
[2018-11-28 06:00:01 +0000] [18884] [INFO] Starting gunicorn 19.9.0
[2018-11-28 06:00:01 +0000] [18884] [INFO] Listening at: http://127.0.0.1:8000 (18884)
[2018-11-28 06:00:01 +0000] [18884] [INFO] Using worker: sync
[2018-11-28 06:00:01 +0000] [18888] [INFO] Booting worker with pid: 18888
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-28 06:00:03.514989: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-28 06:00:03.515818: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-28 06:05:07 +0000] [18884] [INFO] Handling signal: term
[2018-11-28 06:05:07 +0000] [18888] [INFO] Worker exiting (pid: 18888)
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
[2018-11-28 06:05:07 +0000] [18884] [INFO] Shutting down: Master
[2018-11-28 06:05:09 +0000] [19041] [INFO] Starting gunicorn 19.9.0
[2018-11-28 06:05:09 +0000] [19041] [INFO] Listening at: http://127.0.0.1:8000 (19041)
[2018-11-28 06:05:09 +0000] [19041] [INFO] Using worker: sync
[2018-11-28 06:05:09 +0000] [19045] [INFO] Booting worker with pid: 19045
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-28 06:05:10.832815: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-28 06:05:10.833678: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-28 06:06:29 +0000] [19041] [INFO] Handling signal: term
[2018-11-28 06:06:29 +0000] [19045] [INFO] Worker exiting (pid: 19045)
None
(2013, 'Lost connection to MySQL server during query')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
[2018-11-28 06:06:30 +0000] [19041] [INFO] Shutting down: Master
[2018-11-28 06:06:31 +0000] [19233] [INFO] Starting gunicorn 19.9.0
[2018-11-28 06:06:31 +0000] [19233] [INFO] Listening at: http://127.0.0.1:8000 (19233)
[2018-11-28 06:06:31 +0000] [19233] [INFO] Using worker: sync
[2018-11-28 06:06:31 +0000] [19237] [INFO] Booting worker with pid: 19237
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-28 06:06:32.769806: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-28 06:06:32.771053: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away[2018-11-29 18:58:46 +0000] [19233] [INFO] Handling signal: term
[2018-11-29 18:58:46 +0000] [19237] [INFO] Worker exiting (pid: 19237)
')
filesFromDB Failed
[2018-11-29 18:58:46 +0000] [19233] [INFO] Shutting down: Master
[2018-11-29 18:58:48 +0000] [2397] [INFO] Starting gunicorn 19.9.0
[2018-11-29 18:58:48 +0000] [2397] [INFO] Listening at: http://127.0.0.1:8000 (2397)
[2018-11-29 18:58:48 +0000] [2397] [INFO] Using worker: sync
[2018-11-29 18:58:48 +0000] [2401] [INFO] Booting worker with pid: 2401
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-29 18:58:50.864875: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-29 18:58:50.865680: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
[2018-11-30 03:18:02,229] ERROR in app: Exception on /upload [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/SeeFood-Server/index.py", line 36, in upload_file
    results = fileToDB(f)
  File "/home/ubuntu/SeeFood-Server/index.py", line 129, in fileToDB
    db.rollback()
OperationalError: (2006, 'MySQL server has gone away')
[2018-11-30 18:34:06 +0000] [2397] [INFO] Handling signal: term
[2018-11-30 18:34:06 +0000] [2401] [INFO] Worker exiting (pid: 2401)
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
[['6NXLFUP', 'files/6NXLFUP.jpg', -0.226043, 2.2872], ['70O9QGR', 'files/70O9QGR.jpg', 0.604104, 1.4559]]
None
(2013, 'Lost connection to MySQL server during query')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
looking for food in files/04TKOY3.jpg
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
None
(2006, 'MySQL server has gone away')
filesFromDB Failed
[2018-11-30 18:34:06 +0000] [2397] [INFO] Shutting down: Master
[2018-11-30 18:34:08 +0000] [11399] [INFO] Starting gunicorn 19.9.0
[2018-11-30 18:34:08 +0000] [11399] [INFO] Listening at: http://127.0.0.1:8000 (11399)
[2018-11-30 18:34:08 +0000] [11399] [INFO] Using worker: sync
[2018-11-30 18:34:08 +0000] [11403] [INFO] Booting worker with pid: 11403
[2018-11-30 18:34:08 +0000] [11403] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/SeeFood-Server/index.py", line 176
    db.close()
     ^
IndentationError: expected an indented block
[2018-11-30 18:34:08 +0000] [11403] [INFO] Worker exiting (pid: 11403)
[2018-11-30 18:34:08 +0000] [11399] [INFO] Shutting down: Master
[2018-11-30 18:34:08 +0000] [11399] [INFO] Reason: Worker failed to boot.
[2018-11-30 18:34:09 +0000] [11404] [INFO] Starting gunicorn 19.9.0
[2018-11-30 18:34:09 +0000] [11404] [INFO] Listening at: http://127.0.0.1:8000 (11404)
[2018-11-30 18:34:09 +0000] [11404] [INFO] Using worker: sync
[2018-11-30 18:34:09 +0000] [11408] [INFO] Booting worker with pid: 11408
[2018-11-30 18:34:09 +0000] [11408] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/SeeFood-Server/index.py", line 176
    db.close()
     ^
IndentationError: expected an indented block
[2018-11-30 18:34:09 +0000] [11408] [INFO] Worker exiting (pid: 11408)
[2018-11-30 18:34:10 +0000] [11404] [INFO] Shutting down: Master
[2018-11-30 18:34:10 +0000] [11404] [INFO] Reason: Worker failed to boot.
[2018-11-30 18:34:12 +0000] [11414] [INFO] Starting gunicorn 19.9.0
[2018-11-30 18:34:12 +0000] [11414] [INFO] Listening at: http://127.0.0.1:8000 (11414)
[2018-11-30 18:34:12 +0000] [11414] [INFO] Using worker: sync
[2018-11-30 18:34:12 +0000] [11418] [INFO] Booting worker with pid: 11418
[2018-11-30 18:34:12 +0000] [11418] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/SeeFood-Server/index.py", line 176
    db.close()
     ^
IndentationError: expected an indented block
[2018-11-30 18:34:12 +0000] [11418] [INFO] Worker exiting (pid: 11418)
[2018-11-30 18:34:12 +0000] [11414] [INFO] Shutting down: Master
[2018-11-30 18:34:12 +0000] [11414] [INFO] Reason: Worker failed to boot.
[2018-11-30 18:34:15 +0000] [11419] [INFO] Starting gunicorn 19.9.0
[2018-11-30 18:34:15 +0000] [11419] [INFO] Listening at: http://127.0.0.1:8000 (11419)
[2018-11-30 18:34:15 +0000] [11419] [INFO] Using worker: sync
[2018-11-30 18:34:15 +0000] [11423] [INFO] Booting worker with pid: 11423
[2018-11-30 18:34:15 +0000] [11423] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/SeeFood-Server/index.py", line 176
    db.close()
     ^
IndentationError: expected an indented block
[2018-11-30 18:34:15 +0000] [11423] [INFO] Worker exiting (pid: 11423)
[2018-11-30 18:34:15 +0000] [11419] [INFO] Shutting down: Master
[2018-11-30 18:34:15 +0000] [11419] [INFO] Reason: Worker failed to boot.
[2018-11-30 18:36:36 +0000] [11461] [INFO] Starting gunicorn 19.9.0
[2018-11-30 18:36:36 +0000] [11461] [INFO] Listening at: http://127.0.0.1:8000 (11461)
[2018-11-30 18:36:36 +0000] [11461] [INFO] Using worker: sync
[2018-11-30 18:36:36 +0000] [11465] [INFO] Booting worker with pid: 11465
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-11-30 18:36:39.210244: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-30 18:36:39.214805: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
